{
 "title": "Sandbox",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Operator CPU Usage (milli)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'host-operator-.*',namespace=~'.*-host-operator'}*1000",
     "legendFormat": "host-operator"
    },
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'member-operator-.*',namespace=~'.*-member-operator'}*1000",
     "legendFormat": "member-operator"
    },
    {
     "expr": "pod:container_cpu_usage:sum{pod=~'registration-service-.*',namespace=~'.*-host-operator'}*1000",
     "legendFormat": "registration-service"
    }
   ]
  },
  {
   "title": "Active users (total)",
   "type": "gauge",
   "description": "Tracking the total number of MasterUserRecord resources",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sandbox_master_user_record_current)",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Operator Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'host-operator-.*',namespace=~'.*-host-operator',container='',}) BY (pod, namespace)",
     "legendFormat": "host-operator"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'member-operator-.*',namespace=~'.*-member-operator',container='',}) BY (pod, namespace)",
     "legendFormat": "member-operator"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'registration-service-.*',namespace=~'.*-host-operator',container='',}) BY (pod, namespace)",
     "legendFormat": "registration-service"
    }
   ]
  },
  {
   "title": "Activity (rate on 5m)",
   "type": "graph",
   "description": "Tracking evolution of approved, deactivated and banned users",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(sandbox_user_signups_approved_total[5m]))*60",
     "legendFormat": "approved/min"
    },
    {
     "expr": "sum by (service) (rate(sandbox_user_signups_deactivated_total[5m]))*60",
     "legendFormat": "deactivated/min"
    },
    {
     "expr": "sum by (service) (rate(sandbox_user_signups_banned_total[5m]))*60",
     "legendFormat": "banned/min"
    }
   ]
  }
 ]
}